spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deployz
    username: root
    password: deployz
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    generate-ddl: true
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api/swagger-ui.html
  api-docs:
    path: /api/post-docs
deployz:
  rootPath: "/projects"
  logPath: "logs"
  configPath: "config"
